### ISSUE TITLE
Strange error where index.js has a bad reference.

### ISSUE THREAD

**Issue by JoelParke** [bougarfaoui/ng2-socket-io#3]
I ran into an issue today where I kept getting an unable to resolve 'SocketIoConfig'.
I went round and round.  Reinstalled: npm cache clean; npm install;
Did my webpack build and again... hit this issue...
I looked deeper and I found that the installed index.js had on LINE::5

     var SocketIoConfig_1 = require("./SocketIoConfig");

Which was killing the build.   I changed the code in the module to:

     var SocketIoConfig_1 = require("./socketIoConfig");

And all works.  
Did you ever release a version where you had a

     require("./SocketIoConfig")

Or did I just run into some other npm bug or something like that???

**Comment by JoelParke** [comment]
I looked again. 
I did:

     1. npm uninstall 'ng2-socket-io'
     2. npm install --save ng2-socket-io'

Then the build failed in a different way where the check at the end of webpack could not find SocketIoConfig again.
 
Looking into ng2-socket-io/index.ts I see on line 4:

     export { SocketIoConfig } from './SocketIoConfig';

Once I changed that to:

     export { SocketIoConfig } from './socketIoConfig'; 

All is happy.  Please take a look and see if there is some issue with release: 0.1.6 ??  Thanks for the project, it's doing just what I needed.

**Comment by bougarfaoui** [comment]
I just updated the module ( 0.1.7 ) on npm, your problem should be fixed now.
