### ISSUE TITLE
how to catch disconnected event?

### ISSUE THREAD

**Issue by criticalboot** [bougarfaoui/ng2-socket-io#42]
how to check socket is in connected / disconnected state?

**Comment by bougarfaoui** [comment]
like this :
`if(this.socket.ioSocket.connected){ //... } `

**Comment by mer30boy** [comment]
I did this:
`let example = this.socket.ioSocket.connected;`

But when 'this.socket.ioSocket.connected' changes, 'example variable' does not change.
How can I apply the changes in 'example variable' as soon as 'this.socket.ioSocket.connected' changes in angular?
